version: '3.8'

services:
  odoo:
    build: .
    container_name: odoo
    ports:
      - "8069:8069"
    environment:
      - ODOO_HOME=/opt/odoo
      - ODOO_CONF=/opt/odoo/odoo/odoo.conf
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    depends_on:
      - db
    volumes:
      - ./addons:/opt/odoo/odoo/custom-addons
    networks:
      - odoo-net

  db:
    image: "postgres:15"
    container_name: odoo-postgres
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - odoo-net

volumes:
  postgres-data:

networks:
  odoo-net:
    driver: bridge
