services:
  odoo:
    image: alexpdc/odoo_18:latest
    container_name: odoo
    ports:
      - "8069:8069"
    environment:
      - ODOO_HOME=/opt/odoo
      - ODOO_CONF=/opt/odoo/odoo/odoo.conf
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - PYDEVD_PATH=/opt/.pycharm_helpers/pydev
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8069" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - .:/opt/odoo/odoo
      - odoo-filestore:/opt/odoo/data
      - odoo-logs:/var/log/odoo

  db:
    image: "postgres:15"
    container_name: odoo-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U odoo" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres-data:
  odoo-filestore:
  odoo-logs:
